In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("C:\\Users\\amanw\\OneDrive\\Desktop\\project6\\financial_dataset.csv")

In [5]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.head())
print(df.columns)

(10000, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Age                           9500 non-null   float64
 1   Annual_Income                 9500 non-null   float64
 2   Monthly_Expenses              9500 non-null   float64
 3   Savings_Rate                  9500 non-null   float64
 4   Debt_to_Income_Ratio          9505 non-null   float64
 5   Current_Investments_Value     9500 non-null   float64
 6   Total_Loan_Amount             9500 non-null   float64
 7   Avg_Credit_Score              9500 non-null   float64
 8   Inflation_Rate                9500 non-null   float64
 9   Interest_Rate                 9500 non-null   float64
 10  Years_of_Employment           9500 non-null   float64
 11  Job_Stability_Score           9500 non-null   float64
 12  Emergency_Fund_Value          9500 non-null   float64
 13  Retirement_Fund_Contribution  9500 non-null   float64
 14  Customer_Segment              10000 non-null  object
 15  Future_Balance                10000 non-null  float64
dtypes: float64(15), object(1)
memory usage: 1.2+ MB
None
               Age  Annual_Income  Monthly_Expenses  Savings_Rate  \
count  9500.000000   9.500000e+03       9500.000000   9500.000000
mean     40.104000   1.069967e+06      47411.526088      0.286018
std       9.706598   1.063655e+06      28181.118502      0.158427
min      21.000000   3.000000e+05      10311.280000      0.000000
25%      33.000000   6.926435e+05      31632.887500      0.160000
50%      40.000000   9.093829e+05      41796.795000      0.270000
75%      47.000000   1.199309e+06      56158.172500      0.390000
max      65.000000   2.860215e+07     531037.550000      0.900000

       Debt_to_Income_Ratio  Current_Investments_Value  Total_Loan_Amount  \
count           9505.000000               9.500000e+03       9.500000e+03
mean               0.351678               2.274003e+06       8.485883e+05
std                0.244666               1.020151e+06       5.660434e+05
min                0.000000               4.065681e+05       7.906566e+04
25%                0.200000               1.500302e+06       4.609977e+05
50%                0.320000               2.088030e+06       7.074450e+05
75%                0.460000               2.855635e+06       1.063804e+06
max                2.000000               5.000000e+06       5.000000e+06

       Avg_Credit_Score  Inflation_Rate  Interest_Rate  Years_of_Employment  \
count       9500.000000     9500.000000    9500.000000          9500.000000
mean         666.307263        6.006605       7.035445             8.092389
std           43.635712        0.978770       1.467793             4.764537
min          499.000000        3.000000       4.000000             0.000000
25%          637.000000        5.350000       6.020000             4.600000
50%          667.000000        6.000000       7.000000             8.000000
75%          696.000000        6.650000       8.040000            11.400000
max          833.000000       10.000000      12.000000            26.900000

       Job_Stability_Score  Emergency_Fund_Value  \
count          9500.000000           9500.000000
mean              0.302957         226612.075007
std               0.153323         122452.335964
min               0.000000          34247.680000
25%               0.190000         141688.820000
50%               0.300000         199492.950000
75%               0.410000         279561.945000
max               0.920000        1000000.000000

       Retirement_Fund_Contribution  Future_Balance
count                   9500.000000    1.000000e+04
mean                   98428.157903    2.826334e+06
std                    50448.211821    1.203896e+06
min                    15219.190000    5.110349e+05
25%                    62337.455000    1.920633e+06
50%                    88130.220000    2.608302e+06
75%                   122811.030000    3.488464e+06
max                   416528.290000    7.461108e+06
    Age  Annual_Income  Monthly_Expenses  Savings_Rate  Debt_to_Income_Ratio  \
0  45.0      686081.81          17942.27          0.29                  0.25
1   NaN      796474.39          55385.20          0.12                  0.55
2  46.0      708707.11               NaN          0.29                  0.38
3  55.0      940641.40          55378.16          0.11                  0.18
4  38.0     1452826.39          74823.60          0.29                  0.75

   Current_Investments_Value  Total_Loan_Amount  Avg_Credit_Score  \
0                 1807462.47          556913.97             651.0
1                 2935502.53          563982.05             728.0
2                 1569022.45          479932.78             748.0
3                 3154348.23          484769.37             686.0
4                 4180505.40          839038.16             593.0

   Inflation_Rate  Interest_Rate  Years_of_Employment  Job_Stability_Score  \
0            6.69           6.65                  9.4                 0.39
1             NaN           8.25                 17.8                 0.50
2            6.14           7.33                  8.5                 0.44
3            6.04           5.70                 11.8                 0.35
4            5.48           7.91                  5.9                 0.37

   Emergency_Fund_Value  Retirement_Fund_Contribution Customer_Segment  \
0              67331.21                      98811.48           Bronze
1             298162.24                      42078.16           Silver
2             196371.67                      93875.14           Silver
3             108082.97                           NaN           Silver
4             180062.32                      80520.70             Gold

   Future_Balance
0      2227592.16
1      3282530.21
2      2005199.77
3      3674791.61
4      4847001.70
Index(['Age', 'Annual_Income', 'Monthly_Expenses', 'Savings_Rate',
       'Debt_to_Income_Ratio', 'Current_Investments_Value',
       'Total_Loan_Amount', 'Avg_Credit_Score', 'Inflation_Rate',
       'Interest_Rate', 'Years_of_Employment', 'Job_Stability_Score',
       'Emergency_Fund_Value', 'Retirement_Fund_Contribution',
       'Customer_Segment', 'Future_Balance'],
      dtype='object')

In [7]:
num_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()